updated run script

diff --git a/run_database b/run_database
--- a/run_database
+++ b/run_database
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 
+if [ ! -f "DatabaseManager.java" ]; then
+    echo "Error: cannot find the java class"
+    exit 1
+fi
+
 if [ ! -f "DatabaseManager" ]; then
+    echo "Compiling java file"
    javac DatabaseManager.java
 fi
 
